[MI-2385] Fix review fixes for PR GH-774
Brightscout/mattermost-plugin-jira pull request #19
Opened 2022-11-23 10:21 UTC by ayusht2810

2022-11-23 10:47 UTC, raghavaggarwal2308 requested changes

2022-11-23 10:47 UTC, raghavaggarwal2308 commented on webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
> +        }
Do you see any specific reason for making them `null`? If not, I think we can just declare them in one line and they will have their value as `undefined`

2022-11-23 11:00 UTC, raghavaggarwal2308 approved these changes

2022-11-24 08:49 UTC, avas27JTG approved these changes

2022-11-24 08:55 UTC, merged