MM-571: Fixed the issue of receiving Jira subscription after the channel is archived
Brightscout/mattermost-plugin-jira pull request #81
Opened 2024-09-02 13:29 UTC by Kshitij-Katiyar

### Summary
- Fixed the issue of receiving the Jira subscription after the channel is archived

### How to Test
- Create a subscription in a channel and check if the subscription is working
- Archive the channel
- Try sending more subscription events
- Unarchive the channel
#### Current behaviour
- Subscription event notification are received after the channel is archived
#### Updated behaviour
- No subscription event notification received after the channel is archived

2024-09-06 10:49 UTC, raghavaggarwal2308 requested changes

2024-09-06 10:49 UTC, raghavaggarwal2308 commented on server/webhook_worker.go
> +		channel, nErr := ww.p.API.GetChannel(channelSubscribed.ChannelID)
Use p.client if possible

2024-09-06 10:49 UTC, raghavaggarwal2308 commented on server/webhook_worker.go
> +			ww.p.client.Log.Warn("error occurred while getting the channel details while posting the webhook event", "ChannelID", channelSubscribed.ChannelID, "Error", nErr.DetailedError)
```suggestion
			ww.p.client.Log.Warn("Error occurred while getting the channel details while posting the webhook event", "ChannelID", channelSubscribed.ChannelID, "Error", nErr.DetailedError)
```

2024-09-13 11:28 UTC, raghavaggarwal2308 approved these changes

2024-09-17 10:08 UTC, Kshitij-Katiyar commented
Created a PR with all these changes on Mattermost remote hence closing this one.

2024-09-17 10:08 UTC, closed without merging