[MM-1081]: Fixed the rendering of hyperlink in tooltip
Brightscout/mattermost-plugin-jira pull request #86
Opened 2024-09-19 12:51 UTC by Kshitij-Katiyar

### Summary
Fixed the rendering of hyperlink in tooltip
### Screenshots
#### Existing
![Screenshot from 2024-09-19 16-37-55](https://github.com/user-attachments/assets/7af8645c-dda6-4223-83ae-3f79576d8765)
#### Updated
![Screenshot from 2024-09-19 16-36-00](https://github.com/user-attachments/assets/074426a9-983e-47d7-bdb6-0f90c932bfca)

2024-09-19 14:39 UTC, raghavaggarwal2308 commented
@Kshitij-Katiyar THe screenshots are not of tooltips

2024-09-19 18:09 UTC, Kshitij-Katiyar commented
> @Kshitij-Katiyar THe screenshots are not of tooltips

Fixed

2024-09-21 04:17 UTC, raghavaggarwal2308 requested changes

2024-09-21 04:17 UTC, raghavaggarwal2308 commented on webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
> +                        <div dangerouslySetInnerHTML={{__html: preProcessDescription(ticketDetails.description)}}/>
What is the need or using dangerouslySetInnerHTML attribute?

2024-09-21 04:17 UTC, raghavaggarwal2308 commented on webapp/src/components/jira_ticket_tooltip/jira_ticket_tooltip.tsx
> +function preProcessDescription(description: string): string {
Cant we do it on backend side? As the data is coming from there only. We already have a function there to handle all this. Also we are supporting just links here, we need to handle other cases as well

2024-09-26 11:54 UTC, raghavaggarwal2308 approved these changes

2024-09-26 13:23 UTC, Kshitij-Katiyar commented
Created a PR on mattermost remote with all these changes hence closing this one

2024-09-26 13:23 UTC, closed without merging